---
name: 'Connect to AWS'
description: 'Used to connect to AWS'
inputs:
  access-key:
    description: "AWS access-key"
    required: true
  secret-key:
    description: "AWS access-key"
    required: true
  aws-service:
    description: "service required to login to"
    required: true
    default: ECR
runs:
  using: 'composite'
  steps:
    - name: Configure AWS CLI
      shell: bash
      run: |
        aws configure set aws_access_key_id ${{ inputs.access-key }}
        aws configure set aws_secret_access_key ${{ inputs.secret-key }}
    - name: Log in to Amazon ECR
      if: contains(inputs.aws-service, 'ECR')
      shell: bash
      run: |
        echo "ECR_PASSWORD=$(aws ecr get-login-password)" >> $GITHUB_ENV
        echo $ECR_PASSWORD | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - name: Log in to Amazon EKS
      if: contains(inputs.aws-service, 'EKS')
      shell: bash
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME