name: Run Jenkinsfile
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Jenkinsfile
      run: |
        docker run --rm -v  -e ACCESS_KEY "${{ secrets.ACCESS_KEY }}" -e SECRET_KEY "${{ secrets.SECRET_KEY }}" $(pwd)/Jenkinsfile:/workspace/Jenkinsfile jenkins/jenkinsfile-runner
