---
name: Nightly integration tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  pr-1:
    secrets: inherit
    uses: ./.github/workflows/pr.yml
    with:
      from-merge: true

  long-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: long-test
        shell: bash
        run: sleep 500
  
  long-test-2:
    needs: pr-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: long-test
        shell: bash
        run: sleep 500

  pr-2:
    needs: long-test-1
    secrets: inherit
    uses: ./.github/workflows/pr.yml