---
name: PR
on:
  workflow_call:
  pull_request:
    types:
      - synchronize

env:
  REGISTRY: ghcr.io
  CICD_IMAGE: cicd:v1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/python-lint
        with:
          python-version: 3.9
    
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/get-pytest
        with:
          python-version: 3.9
      - name: Run pytest
        run: pytest

  run_in_container:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.REGISTRY }}/${{ env.CICD_IMAGE }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - my_docker_volume:/volume_mount
    steps:
      - name: test
        run: ls
