---
name: PR
on:
  workflow_call:
  pull_request:
    types:
      - synchronize

env:
  DOCKER_REGISTRY: ghcr.io
  CICD_IMAGE: xaxis-code/cicd:v1
  ACCOUNTID: 952256534162
  IMAGE_NAME: experiment-ga
  AWSZONE: us-east-1
  REPO_NAME: 952256534162.dkr.ecr.us-east-1.amazonaws.com

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/python-lint
        with:
          python-version: 3.9
    
  setup_aws:
    runs-on: ubuntu-latest
    outputs:
      ecr_password: ${{ steps.connect_aws.outputs.ecr_password }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: prove secrets exist
        run: echo "ak ${{ secrets.ACCESS_KEY }} sk ${{ secrets.SECRET_KEY }}"
      - name: Connect to AWS
        uses: ./.github/actions/aws-connect
        id: connect_aws
        with:
          access-key: ${{ secrets.ACCESS_KEY }}
          secret-key: ${{ secrets.SECRET_KEY }}
          aws-service: ECR
          aws-region: ${{ env.AWSZONE }}
          aws-account: ${{ env.ACCOUNTID }}

  test:
    needs: 
      - lint
      - setup_aws
    runs-on: ubuntu-latest
    container:
      image: 952256534162.dkr.ecr.us-east-1.amazonaws.com/cicd:2023.08.28-yaakov.yekezkel-4194fc1
      credentials:
        username: AWS
        password: ${{ needs.setup_aws.outputs.ecr_password }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/get-pytest
        with:
          python-version: 3.9
      - name: Run pytest
        run: pytest --junitxml=output.xml
      - name: Upload output.xml as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-xml
          path: output.xml

  test-v2:
    needs: 
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Connect to AWS
        uses: ./.github/actions/aws-connect
        id: connect_aws
        with:
          access-key: ${{ secrets.ACCESS_KEY }}
          secret-key: ${{ secrets.SECRET_KEY }}
          aws-service: ECR
          aws-region: ${{ env.AWSZONE }}
          aws-account: ${{ env.ACCOUNTID }}
      - name: Run tests in Docker container
        run: |
          docker run -v ${{ github.workspace }}:/workspace -w /workspace 952256534162.dkr.ecr.us-east-1.amazonaws.com/cicd:2023.08.24-oliver-e6a30eb /bin/bash -c "pip install pytest -r requirements.txt && /home/devops/.local/bin/pytest"
