---
name: PR
on:
  workflow_call:
  pull_request:
    types:
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/python-lint
        with:
          python-version: 3.9
    
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/get-pytest
        with:
          python-version: 3.9
      - name: Run pytest
        run: pytest

  run_in_container:
    needs: scheduled_job
    container:
      image: 952256534162.dkr.ecr.us-east-1.amazonaws.com/cicd:2023.08.24-oliver-e6a30eb
      credentials:
         username: AWS
         password: ${{ secrets.ECR_DOCKER_LOGIN_PWD }}
      volumes:
        - my_docker_volume:/volume_mount
